### Numpy Library Learning

In [3]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
a.shape


(2, 3)

In [4]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
a[4]

np.int64(5)

In [6]:
a[1] = 100

In [7]:
a

array([  1, 100,   3,   4,   5,   6,   7,   8])

In [8]:
a[:3]

array([  1, 100,   3])

In [9]:
b = a[3:]

In [10]:
b

array([4, 5, 6, 7, 8])

In [11]:
b[1] = 14
b

array([ 4, 14,  6,  7,  8])

In [12]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
d 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
d[2,1]

np.int64(8)

In [14]:
### Number of Dimensions using Ndim Function

d.ndim

2

In [15]:
### To check the shape of an array using shape function
d.shape

(3, 3)

In [16]:
## To check the size of an Array using size method or function

d.size

9

In [17]:
#### How To Create Basic Array

np.zeros(4)

array([0., 0., 0., 0.])

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [20]:
### Linear Space Interval 
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [21]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.array([10,20,30,40,50,60])

np.concatenate((a,b))

np.concatenate((a,b),axis=0)


array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 20, 30, 40, 50, 60])

In [22]:
### Reshape An Array 
a = np.arange(6)
print(a)
b = a.reshape(3,2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [23]:
five_up = (a>5) | (a==5)
print(five_up)

[False False False False False  True]


In [28]:
arr1 = np.array([1,2,3,4,5])
np.sqrt(arr1)
np.exp(arr1)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [29]:
a = np.array([1,2,3,4,5,6,7,8,9,10]) 
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [32]:
np.save('Numpy_Array',a)

In [33]:
np.load('Numpy_Array.npy')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
csv_arr = np.array([[1,2,3,4,5],[9,8,7,6,5]])

In [35]:
print(csv_arr)

[[1 2 3 4 5]
 [9 8 7 6 5]]


In [36]:
np.savetxt('npfile.csv',csv_arr)

In [39]:
data = np.array([[1,2],[3,4],[5,6],[7,8],[9,0]])
print(data)

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]


In [41]:
print(data[0,1])

2


In [42]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [43]:
data[0:2,0]

array([1, 3])

In [44]:
data.max(axis=1)

array([2, 4, 6, 8, 9])

In [46]:
data.min(axis=1)

array([1, 3, 5, 7, 0])

In [48]:
rng = np.random.default_rng()

In [49]:
rng.random((3,2))

array([[0.27030506, 0.53549852],
       [0.36383273, 0.54193089],
       [0.93231076, 0.48075949]])

In [ ]:
### Nunmbers 5 And size would be 2 rows and 4 columns

rng.integers(5,size=(2,4))

array([[3, 0, 4, 2],
       [1, 1, 2, 1]])

In [53]:
x= np.arange(9).reshape(3,3)

In [57]:
np.add.reduce(x,1)
y = np.add.reduce(x,(0,1))
print(y)

36


In [4]:
import numpy as np

sales = [0,0.5,5,155,239,3.4,5.9]
sales_data = np.array(sales)
print(sales_data)

print(f"The N-Dimension ", sales_data.ndim)
print(f"The Shape of Data", sales_data.shape)
print("The size of Array", sales_data.size)





[  0.    0.5   5.  155.  239.    3.4   5.9]
The N-Dimension  1
The Shape of Data (7,)
The size of Array 7


In [5]:
np.random.randn(3)

array([-0.11753793,  0.43166168, -0.28793684])

In [7]:
np.random.randint(1,100)

37

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
randarr = np.random.randint(0,25,5)

In [22]:
randarr.max()

np.int64(21)

In [23]:
randarr.min()

np.int64(8)